In [27]:
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
import numpy as np

In [28]:
# fazendo a leitura dos dados
iris = load_iris()
iris_data = iris.data
m, n = iris_data.shape

print('Numero de observações:', m)
print('Numero de variaveis:', n)

Numero de observações: 150
Numero de variaveis: 4


In [29]:
# ajustando o algoritmo com tres centros e definir onde o centroide começará
km = KMeans(n_clusters=3, random_state=0)
km.fit(iris_data)

KMeans(n_clusters=3, random_state=0)

In [30]:
# Verificando se algoritmo classificou corretamente 
y_iris = iris.target
for i in range(m):
    print('{0} {1} {2}'.format(i, km.labels_[i], y_iris[i]))


0 1 0
1 1 0
2 1 0
3 1 0
4 1 0
5 1 0
6 1 0
7 1 0
8 1 0
9 1 0
10 1 0
11 1 0
12 1 0
13 1 0
14 1 0
15 1 0
16 1 0
17 1 0
18 1 0
19 1 0
20 1 0
21 1 0
22 1 0
23 1 0
24 1 0
25 1 0
26 1 0
27 1 0
28 1 0
29 1 0
30 1 0
31 1 0
32 1 0
33 1 0
34 1 0
35 1 0
36 1 0
37 1 0
38 1 0
39 1 0
40 1 0
41 1 0
42 1 0
43 1 0
44 1 0
45 1 0
46 1 0
47 1 0
48 1 0
49 1 0
50 0 1
51 0 1
52 2 1
53 0 1
54 0 1
55 0 1
56 0 1
57 0 1
58 0 1
59 0 1
60 0 1
61 0 1
62 0 1
63 0 1
64 0 1
65 0 1
66 0 1
67 0 1
68 0 1
69 0 1
70 0 1
71 0 1
72 0 1
73 0 1
74 0 1
75 0 1
76 0 1
77 2 1
78 0 1
79 0 1
80 0 1
81 0 1
82 0 1
83 0 1
84 0 1
85 0 1
86 0 1
87 0 1
88 0 1
89 0 1
90 0 1
91 0 1
92 0 1
93 0 1
94 0 1
95 0 1
96 0 1
97 0 1
98 0 1
99 0 1
100 2 2
101 0 2
102 2 2
103 2 2
104 2 2
105 2 2
106 0 2
107 2 2
108 2 2
109 2 2
110 2 2
111 2 2
112 2 2
113 0 2
114 0 2
115 2 2
116 2 2
117 2 2
118 2 2
119 0 2
120 2 2
121 0 2
122 2 2
123 0 2
124 2 2
125 2 2
126 0 2
127 0 2
128 2 2
129 2 2
130 2 2
131 2 2
132 2 2
133 0 2
134 2 2
135 2 2
136 2 2
137 2 2
138 0 

In [31]:
# montando uma matriz de frequencia/confusão observa-se que ouve muitos erros na classificação de um de uma das espécies. Isso indicando que existe uma maior aproximação dessas obsevação para a espécie da qual elas não pertencem.

Mapa = np.zeros((3,3))
for i in range(m):
    Mapa[y_iris[i]][km.labels_[i]] += 1
print(Mapa)

[[ 0. 50.  0.]
 [48.  0.  2.]
 [14.  0. 36.]]
